restaurant_data = [
    "You can reserve a table by calling 042-111-333-555 or through our website.",
    "We are open from 1pm to 11pm every day.",
    "We serve Pakistani, Italian, and Chinese cuisine.",
    "Our address is 123 Wapda Town, Lahore.",
    "Yes, we have vegetarian, vegan, and gluten-free options.",
    "You can order food online via our mobile app or FoodPanda.",
    "We offer dine-in, takeaway, and delivery services.",
    "Our lunch deal includes biryani, raita, and a drink for just Rs. 499.",
    "We have a family platter with BBQ, karahi, naan, and drinks for Rs. 1999.",
    "All our food is halal and prepared fresh daily.",
    "Yes, we have indoor and outdoor seating available.",
    "Our most popular items are Chicken Karahi, BBQ Plater, and Seekh Kebabs.",
    "Kids meals include nuggets, fries, and juice for Rs. 299.",
    "We accept cash, debit/credit cards, and Easypaisa.",
    "You can host birthday parties and private events with us.",
    "Please call ahead to confirm availability for large groups.",
    "We provide high chairs for children and wheelchair access.",
    "Our chefs specialize in Desi and tandori dishes.",
    "The average wait time is 15–20 minutes for dine-in.",
    "We offer a weekend brunch from 11 AM to 2 PM.",
    "Hello! How can I assist you today?",
    "Hi there! How can I help you?",
    "Good day! What can I do for you?",
    "Welcome to our restaurant! How can I assist you?",
]
